plugins {
    id 'org.jetbrains.kotlin.jvm'
}

tasks.named('jar', Jar) {
    manifest {
        attributes["Main-Class"] = 'com.majeur.inputmethod.tools.emoji.MakeEmojiKeys'
    }
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register('makeEmoji', JavaExec) {
    dependsOn tasks.named('jar')
    mainClass = 'com.majeur.inputmethod.tools.emoji.MakeEmojiKeys'
    classpath = files(tasks.named('jar').flatMap { it.archiveFile })
    args '-res', project.rootProject.project('app').projectDir.path + File.separator + 'src' + File.separator + 'main' + File.separator + 'res'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}