plugins {
    id 'java'
}

tasks.named('jar', Jar) {
    manifest {
        attributes["Main-Class"] = 'com.android.inputmethod.keyboard.tools.MakeKeyboardText'
    }
}

tasks.register('makeText', JavaExec) {
    dependsOn tasks.named('jar')
    mainClass = 'com.android.inputmethod.keyboard.tools.MakeKeyboardText'
    classpath = files(tasks.named('jar').flatMap { it.archiveFile })
    args '-java', project.rootProject.project('app').projectDir.path + File.separator + 'src' + File.separator + 'main' + File.separator + 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}